### ISSUE TITLE
Sometimes returns Network Broadcast Address

### ISSUE THREAD

**Issue by begleysm** [phoemur/ipgetter#21]
I wrote a script that uses ipgetter.  It has been running every hour, on two different machines, for weeks.  In two instances (both from the same machine) my script has returned that my external IP is 192.168.0.255 (the Network Broadcast Address in my network).  Has this ever happened to you?  I suspect that, perhaps, one of the randomly selected "whatismyip" websites isn't behaving.

Thoughts?  If you don't have any specific ideas I'll probably run through all of them and see if one is coming back wonky.

Thanks,
begleysm

**Comment by begleysm** [comment]
I figured it out.  I suspected that some of the servers in the list didn't work anymore.  I wrote a test program to try each server and print out the results.  Sure enough, several of the servers didn't work and a check in Firefox suggested they changed their format or went offline.

Humorously, I forked the repo, went to update the list and found that it was already updated?!  I had been using the version from the PIP installer and it looks like phoemur updated the list 7 days ago?!

Oh well, glad it's updated now.  Closing this issue.

**Comment by phoemur** [comment]
Maybe some servers are not working anymore. I haven't had attention to this for some time.
You could try the IPgetter.test() function that tests all servers and returns some of the broken.

I made this and also figured out that some are not broken, they're just slow and as we have a timeout of 2 seconds the do not show correctly
