### ISSUE TITLE
New Project Alert

### ISSUE THREAD

**Issue by begleysm** [phoemur/ipgetter#22]
@phoemur 

I just wanted to let you know that I'm using your code in a project I call "ipwatch".  It uses ipgetter to check the current external IP address of a machine.  It compares that value against a saved "old IP", and if they differ, dispatches an email to let me know of the change.  I use this for keeping track of any IP changes at remote locations.

Thanks for writing ipgetter.

My project is  at https://github.com/begleysm/ipwatch

**Comment by phoemur** [comment]
OK
