### ISSUE TITLE
At least one server will return incorrect IP address

### ISSUE THREAD

**Issue by texasaggie97** [phoemur/ipgetter#23]
I am using 0.6 from PyPI (via pip), so this may be fixed once a new version is created and uploaded.

At least one server will occasionally return an incorrect IP address of '192.168.0.255'

I am trying to use this package in my own program but had to add a workaround for this.

I don't know if there will be other incorrect addresses returned. This is the only one I have seen so far though.

**Comment by phoemur** [comment]
Please run

>>> import ipgetter
>>> ipgetter.IPgetter().test()

and post it here.
Note I uploaded a new version today (0.7)
tx

**Comment by phoemur** [comment]
Isn't this the same as Issue https://github.com/phoemur/ipgetter/issues/21 ?

**Comment by texasaggie97** [comment]
Yes it is. I missed that somehow. Closing this since it is a duplicate.
