### ISSUE TITLE
Hangs on ipgetter.myip()

### ISSUE THREAD

**Issue by kdeltared** [phoemur/ipgetter#24]
Hi,

I'm using ipgetter to get the IP and found that it randomly hangs in `ipgetter.myip()` call.

Versions:
* OS: Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.10-1kali2 (2017-11-08) x86_64 GNU/Linux
* Python: Python 2.7.14+
* Ipgetter: 0.6

**Comment by phoemur** [comment]
I uploaded new version today. Seems OK, but if you feel it is still hanging, please reopen an issue.
Note that ipgetter may have a high timeout, since it waits at most 4 seconds for a server to reply and it has a list of 40 servers.
Best regards.
