### ISSUE TITLE
What do you think about having a limit for the loop in get_externalip?

### ISSUE THREAD

**Issue by robertsdotpm** [phoemur/ipgetter#7]
So I was thinking maybe there should be a limit of say 5 checks in the get_externalip loop (and possibly lower.)  If you assume a timeout of 2 seconds and there's a network fault you're currently stuck having to check for a total of len(self.server_list) * self.timeout which is 90 seconds in my fork.

I know this is only a simple script and maybe I'm over complicating things but it seems to me it should fail earlier rather than blocking a whole program for an indefinite amount of time (this bug has already bitten me simply because I use it literally every day :coffee: under many different conditions )

**Comment by phoemur** [comment]
It's fair, i don't want it locking up everything for 90 seconds either.
I've put 7 checks with a timeout of 2 seconds, for a maximum of 14 seconds...
